import { Link, Navigate, useParams } from 'react-router-dom';
import { ArrowRight, BarChart3, CalendarDays, CarFront, ChevronRight, CircleGauge, PackageOpen, Plus, RadioTower, UsersRound } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import { useAuth } from '../lib/auth';

const units = {
  wash: { name: 'Wash', descriptor: 'Vehicle care & detailing', icon: CarFront, colour: 'bg-[#DFF7F3] text-[#08756D]', hero: 'bg-[#0A625E]', action: '/wash/pos', actionLabel: 'Start a sale', tasks: [['Point of sale', 'Serve the next vehicle', '/wash/pos'], ['Bookings', 'Manage today’s queue', '/bookings'], ['Shifts & till', 'Open or reconcile a shift', '/shifts'], ['Performance', 'Review revenue and visits', '/dashboard']] },
  parts: { name: 'Parts', descriptor: 'Retail & trade supply', icon: PackageOpen, colour: 'bg-[#FFF1D6] text-[#A9550B]', hero: 'bg-[#88450D]', action: '/parts/operations', actionLabel: 'Open sales counter', tasks: [['Sales counter', 'Build and post a parts sale', '/parts/operations'], ['Inventory', 'Stock, pricing and availability', '/parts/operations'], ['Customers', 'Search shared customer history', '/customers'], ['Performance', 'Review Parts revenue', '/dashboard']] },
  drive: { name: 'Drive', descriptor: 'Accessories & fitment', icon: CircleGauge, colour: 'bg-[#EEE9FF] text-[#6046B5]', hero: 'bg-[#51408D]', action: '/drive/operations', actionLabel: 'Book a fitment', tasks: [['New fitment', 'Book an installation job', '/drive/operations'], ['Job board', 'Manage work in progress', '/drive/operations'], ['Customers', 'Search shared customer history', '/customers'], ['Performance', 'Review Drive revenue', '/dashboard']] },
  track: { name: 'Track', descriptor: 'Security & fleet', icon: RadioTower, colour: 'bg-[#E4F5E8] text-[#287242]', hero: 'bg-[#285E3B]', action: '/track/operations', actionLabel: 'Manage tracking', tasks: [['New subscription', 'Onboard customer and vehicle', '/track/operations'], ['Devices', 'Register and allocate units', '/track/operations'], ['Renewals', 'Protect recurring revenue', '/track/operations'], ['Customers', 'Search shared customer history', '/customers']] },
} as const;

export default function BusinessWorkspace() {
  const { business } = useParams(); const { canOperate } = useAuth(); const unit = units[business as keyof typeof units];
  if (!unit || !business || !canOperate(business)) return <Navigate to="/" replace />; const Icon = unit.icon;
  return <div className="mali-page"><div className="mali-page-inner">
    <PageHeader eyebrow={`Mali ${unit.name}`} title={unit.descriptor} description={`Everything your team needs to operate Mali ${unit.name}, connected to the group customer and loyalty foundation.`} action={<Link to={unit.action} className="inline-flex h-11 items-center gap-2 rounded-xl bg-ink-950 px-4 text-sm font-extrabold text-white hover:bg-brand-800"><Plus className="h-4 w-4" /> {unit.actionLabel}</Link>} />
    <section className={`relative overflow-hidden rounded-[1.5rem] ${unit.hero} p-7 text-white shadow-lg sm:p-10`}><Icon className="absolute -bottom-12 -right-5 h-52 w-52 text-white/[.07]" strokeWidth={1}/><div className="relative max-w-2xl"><span className="text-[11px] font-extrabold uppercase tracking-[.16em] text-white/50">Operating principle</span><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-4xl">Recognise the customer.<br/>Complete the job. Build loyalty.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/65">Every completed sale belongs to the unified Mali ledger and strengthens the customer’s group-wide profile.</p></div></section>
    <section><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black text-ink-950">What do you need to do?</h2><span className="hidden text-xs font-bold uppercase tracking-wider text-ink-400 sm:block">Mali {unit.name} workspace</span></div><div className="grid overflow-hidden rounded-[1.5rem] border border-ink-200 bg-white shadow-sm md:grid-cols-2">{unit.tasks.map(([title, detail, path], index) => <Link key={title} to={path} className={`group flex min-h-36 items-center gap-5 p-6 sm:p-7 hover:bg-ink-50 ${index % 2 ? 'md:border-l' : ''} ${index > 1 ? 'border-t' : index === 1 ? 'border-t md:border-t-0' : ''} border-ink-200`}><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl ${unit.colour}`}><span className="font-mono text-xs font-black">0{index + 1}</span></span><div className="min-w-0 flex-1"><h3 className="font-extrabold text-ink-950">{title}</h3><p className="mt-1.5 text-sm text-ink-500">{detail}</p></div><ChevronRight className="h-4 w-4 text-ink-300 transition-transform group-hover:translate-x-1" /></Link>)}</div></section>
    <section className="grid gap-4 md:grid-cols-3"><Link to="/customers" className="flex items-center gap-4 rounded-2xl border border-ink-200 bg-white p-5 hover:border-brand-300"><UsersRound className="h-5 w-5 text-brand-700"/><div><p className="font-extrabold text-ink-950">Customer 360</p><p className="mt-1 text-xs text-ink-500">History across every business</p></div></Link><Link to="/dashboard" className="flex items-center gap-4 rounded-2xl border border-ink-200 bg-white p-5 hover:border-brand-300"><BarChart3 className="h-5 w-5 text-brand-700"/><div><p className="font-extrabold text-ink-950">Intelligence</p><p className="mt-1 text-xs text-ink-500">Revenue and performance</p></div></Link><Link to="/growth" className="flex items-center gap-4 rounded-2xl border border-ink-200 bg-white p-5 hover:border-brand-300"><CalendarDays className="h-5 w-5 text-brand-700"/><div><p className="font-extrabold text-ink-950">Growth</p><p className="mt-1 text-xs text-ink-500">Retention and opportunities</p></div><ArrowRight className="ml-auto h-4 w-4 text-ink-300"/></Link></section>
  </div></div>;
}
